default: &default
  adapter: postgresql
  encoding: unicode
  username:
  password:
  pool: 5

development:
  <<: *default
  database: receta_development

test:
  <<: *default
  database: receta_test

production:
  <<: *default
  database: receta_production
  username: receta
  password: <%= ENV['RECETA_DATABASE_PASSWORD'] %>
